### ISSUE TITLE
Evo Menu Bind Issue

### ISSUE THREAD

**Issue by Wemic46** [GHmods/scze#1]
The bind that allows you to go into the evolution menu should be TAB, the issue is that tab is the score menu for SVEN. For whatever reason, the bind did not carry over for the mod, so instead of being given the ability to evolve, I instead can see the scoreboard.

**Comment by GHmods** [comment]
Hi @Wemic46 , original mod has custom menu instead of scoreboard and its inside game dll (c++).In sven i think scoreboard can't be modified through AngelScript, so instead i made Zombie/Headcrab Class and Ability System. You can use the gene points to unlock them with chat commands:
### For Zombie Players:
-say /zc,/zclass or /zombie_class - visit Zombie Class Menu.
-say /za, /upgrades,/ability or /abilities - visit Zombie Ability Menu.
### For Headcrab Players:
-say /hc or /hclass - visit Headcrab Class Menu.
-say /ha,/hca,/hc_ability or /hc_upgrades - visit Headcrab Ability Menu.
